[workspace]
members = ["crates/*", "tools/*"]
resolver = "3"

[workspace.package]
authors = ["Travis Brown <travisrobertbrown@gmail.com>"]
repository = "https://github.com/travisbrown/archivindex-wordpress"
keywords = ["wordpress", "web", "archive"]
edition = "2024"
rust-version = "1.97"
readme = "README.md"
license = "GPL-3.0-only"
version = "0.1.0"

[workspace.dependencies]
archivindex-archiver = { version = "0.1.0", git = "https://github.com/travisbrown/archivindex-warc" }
archivindex-cli-support = { version = "0.1.0", git = "https://github.com/travisbrown/archivindex" }
archivindex-publication = { version = "0.1.0", git = "https://github.com/travisbrown/archivindex" }
archivindex-test-support = { git = "https://github.com/travisbrown/archivindex" }
archivindex-warc = { version = "0.1.0", git = "https://github.com/travisbrown/archivindex-warc", default-features = false }
archivindex-warc-ops = { version = "0.1.0", git = "https://github.com/travisbrown/archivindex-warc" }
archivindex-wordpress-model = { version = "0.1.0", path = "crates/model" }
archivindex-wordpress-scraper = { version = "0.1.0", path = "crates/scraper" }
chrono = "0.4"
clap = { version = "4.5", features = ["derive"] }
flate2 = { version = "1", default-features = false, features = ["miniz_oxide"] }
humantime = "2"
indicatif = "0.18"
log = "0.4"
proptest = "1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tempfile = "3"
test-strategy = "0.4"
thiserror = "2"
url = "2"

[workspace.lints.rust]
missing_docs = "deny"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
missing_errors_doc = "allow"
